### ISSUE TITLE
Can I have a pre-trained model to make some researches?

### ISSUE THREAD

**Issue by ultraman-blazar** [yliess86/PaintsTorch#1]
Hi @yliess86 , 

I saw your work and found it was really cool to have such amazing results. I'm a student who has lots of interest in image processing; however, I didn't have a powerful GPU like V100 to train the model.

I tried your code and make some modification to adapt to my environment, but per epoch takes about 3-4h, it is too slow to see the results.

If you can provide a pre-trained model for me to play with, it does help me a lot. 

Really sorry for bothering you.

Best regards,
Nisekoixmy.

**Comment by yliess86** [comment]
Hi @Nisekoixmy,

Thank you for your interest.
Unfortunately, we are not allowed to distribute the model's weight, nor the dataset for legal issues.
As you may understand the illustrations do not belong to us but to their original creators.
Thus, as we do not own those rights, we are not allowed to publish the weights.

In fact, we trained the model for about a week. And the previous state of the art we based our work on also trained on long periods with powerful GPUs. The only advice I could give you is to look for cloud instances such as AWS, Google, Lambda, and such.

Regards,
Yliess HATI

**Comment by ultraman-blazar** [comment]
> Hi @Nisekoixmy,
> Thank you for your interest.
> Unfortunately, we are not allowed to distribute the model's weight, nor the dataset for legal issues.
> As you may understand the illustrations do not belong to us but to their original creators.
> Thus, as we do not own those rights, we are not allowed to publish the weights.
> In fact, we trained the model for about a week. And the previous state of the art we based our work on also trained on long periods with powerful GPUs. The only advice I could give you is to look for cloud instances such as AWS, Google, Lambda, and such.
> Regards,
> Yliess HATI

Thank you for a quick replying. I will try to collect some data to train the model by myself. Btw, thank you for such a kind of great work!

Best,
Nisekoixmy.
